# theme = "solarized-dark"
# icons = "awesome"

[[block]]
block = "disk_space"
format = " $available "
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
interval = 300
#warning = 20.0
#alert = 10.0

[[block]]
block = "memory"
# display_type = "memory"
format = " $mem_used / $mem_total($mem_used_percents) "
# format_swap = "{swap_used}/{swap_total}({swap_used_percents})"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
# format = "{1m}"

# [[block]]
# block = "net"
# device = "wlp4s0b1"
# signal_strength = true
# speed_up = false
# speed_down = false
# interval = 5

[[block]]
block = "battery"
interval = 10
format = " $percentage "
full_format = " $percentage "
charging_format = " $percentage "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %d/%m %R') "

# [[block]]
# block = "time"
# interval = 60
# format = "%a %d/%m %R"
